### ISSUE TITLE
Conflict with copic 2

### ISSUE THREAD

**Issue by liquid-me** [CreatureSurvive/motuumLS-IssueTracker#16]
I have a crazy issue with copic 2:
Usually I use round contact pics within copic.
Since the last motuumLS update they are squared...

**Comment by CreatureSurvive** [comment]
Thats a strange issue, I'll look into it. Could you tell me the exact version this popped up in, I released 3 versions 2 days ago.

**Comment by liquid-me** [comment]
It was the latest version... - Thanks!
I also post my tweaklist just in case

7-zip (POSIX): 4.57-3p
Activator: 1.9.13~beta1
App Admin: 1.0r-71
Apple File Conduit "2": 1.2
AppList: 1.5.13
APT 0.6 Transitional: 1:0-23
APT 0.7 (apt-key): 0.7.25.3-3
APT 0.7 Strict (lib): 0.7.25.3-14
APT 0.7 Strict: 0.7.25.3-8
Base Structure: 1-4
Berkeley DB: 4.6.21-5
betterFiveColumnHomescreen: 1.0.1
betterFiveIconDock: 1.0.4
BigBoss Icon Set: 1.0
BlurryBadges: 1.1
Bourne-Again SHell: 4.0.44-16
BrowserBreadcrumbCleanup: 2.0-1
bzip2: 1.0.5-8
Calendar for Lockscreen 2: 1.1.1
CallerIDToggle: 0.0.1-88
CalSwitch10: 1.0.0~beta2
Cephei: 1.11
Copic 2: 1.0.5
Core Utilities (/bin): 8.12-9
Core Utilities: 8.12-13
CrashReporter: 1.15.0-1
Cream 2: 1.1-1
Cydia Installer: 1.1.30
Cydia Substrate: 0.9.6301
Cydia Translations: 1.1.12
Darwin Tools: 1-5
Debian Packager: 1.18.10-12
Debian Utilities: 3.3.3ubuntu1-1p
Diff Utilities: 2.8.1-6
Extender: Reloaded: 0.3.3
Fascy: 1.0.1-2
Filza File Manager: 3.3.2
Find Utilities: 4.2.33-7
Flame: 1.3
FlipControlCenter: 1.0.4
Flipswitch: 1.0.16~beta1
ForceInPicture: 0.0.1-2
FVideo: 0.4-1
GNU Privacy Guard: 1.4.8-4
grep: 2.5.4-3
gzip: 1.6-7
HideMeX (iOS 10): 1.0.10
Horseshoe: 2.1.1
iCleaner Pro: 7.6.1
IconSupport: 1.10.0.2-1
iOS Firmware: 10.2
iPhone Firmware (/sbin): 0-1
KarenLocalizer: 1.0
KarenPrefs: 1.0.1
libarrays: 1.0.7-beta-4
libcolorpicker: 1.6-1
libcrashreport: 1.1.0-1
libCSColorPicker: 0.5.3
libGitHubIssues: 0.0.1
libmoorecon: 0.9.9.0~beta4-1
libpackageinfo: 1.1.0.1-1
libSpringPlus: 0.0.2
libsymbolicate: 1.9.0-1
Link Identity Editor: 1:1.2.1
Lithium Ion: 1.3
LZMA Utils: 4.32.7-5
Messages (iOS 8 & 9 & 10): 1.3.2
mikoto: 3.0.8
motuumLS: 3.0.0.7b
MTerminal: 1.4-5
New Curses: 5.7-15
NextAlarm10: 1.0.0~beta1-10
No Blurry Calls: 1.1-1
OpenNotifier10 - tateu: 2.5.0~beta5-2
PalBreak: 1.1
PAM (Apple): 32.1-4
PAM Modules: 36.1-5
Patcyh: 1.2.0
Perpetual10 Lite: 1.0.0
PreferenceLoader: 2.2.4~alpha1
Profile Directory: 0-2
QRC: 1.1.6-1
readline: 6.0-8
RocketBootstrap: 1.0.5
sed: 4.1.5-8
shell-cmds: 118-7
Sonus: 3.0.2-3
SpringPlus: 1.3-2
Stock for OpenNotifier: 1.9.2
Substrate Safe Mode: 0.9.6001
SwipeSelection: 1.5.2-1
system-cmds: 433.8-14
Tage: 1.2.2-1
Tape Archive: 1.29-10
TapTapFolder: 0.3.8
TechSupport Framework: 1.5.0.1-1
uasharedtools: 2.1r-67
UIKit Tools: 1.1.12
Unify: 1.1.3.2
unrar: 3.6.8-2p
unzip: 5.52-5p
YouTubed: 1.7.2-1
zip: 2.32-5p


--

**Comment by CreatureSurvive** [comment]
Sorry I never got back to you on this, it it still an issue?

**Comment by liquid-me** [comment]
Hi Dana,

Yes it's still an issue on my end...
Thanks 

Willem

--

**Comment by CreatureSurvive** [comment]
Can you confirm if this is still an issue? I'd like to close or fix this.

**Comment by liquid-me** [comment]
It's fine now :)
Thank you!

**Comment by CreatureSurvive** [comment]
Alright thanks, I will close this then.
